### ISSUE TITLE
How would I include a SQLite database with this template?

### ISSUE THREAD

**Issue by Imaginativeone** [Deluze/electron-vue-template#12]
Would I need to place all of the database-oriented files into the "static files folder"?

**Comment by Deluze** [comment]
Depends.

- Do you want to ship a SQLite DB with pre-defined data? If so, adding it to the static directory would be the easiest solution.

- You can also choose to utilize Electron Builder, I would recommend reading [this resource](https://www.electron.build/configuration/contents.html). You can define a path to your SQLite DB in there and tell Electron Builder to copy it to a specific location when the app is getting bundled.

- If your database doesn't contain any pre-defined data I think the most logical step would be to generate a SQLite DB on the user's machine during runtime.

All 3 are completely valid options. I recommend moving the SQLite db when your app is run for the first time to the appData directory (`app.getPath('appData')`).

**Comment by Deluze** [comment]
Also, I think this issue has less to do with the template itself, and rather on how you should handle these files in an Electron app. I honestly have never used SQLite with Electron, but I bet there are useful resources out there on the internet.

**Comment by Imaginativeone** [comment]
Mr. Graham,

First, a million thanks for your updates and explanations.

I created an .env file and wrote these values to it. Regrettably, the default path persists. How do I make the changes stick?

NODE_ENV=local
NODE_STORAGE_PATH=documents
NODE_STORAGE_PATH_EXTRA=/Users/imaginativeone/Documents/Software-Development/Electron/electron-sqlite-vue-tailwind
NODE_STORAGE_PATH_DATABASE_EXTRA=/database

Thanks,

Doug

**Comment by Imaginativeone** [comment]
Mr. Ramaekers,

I wanted to make sure to acknowledge you as well.

Doug
