### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by Dysey** [Deluze/electron-vue-template#13]
Hi, 

I install vue-router and try in createWindow to change the loadFile like that
```js
updateWindow.loadFile(Path.join(app.getAppPath(), 'renderer', 'index.html#splash'));
```
But got an error
`Not allowed to load local resource: file:///C:/laragon/www/temp/dist/win-unpacked/resources/app.asar/renderer/index.html%23splash`

How I create Router
```js
const router = createRouter({
  history: createWebHistory(),
  routes,
});

export default router;
```

Some help pls :) thx a lot

**Comment by Deluze** [comment]
This error you're getting has nothing to do with VueRouter itself.

You're trying to load in an index.html file with an anchor included. That's impossible.

You want to do something like the following:

```js
updateWindow.loadFile(Path.join(app.getAppPath(), 'renderer', 'index.html'),  { hash: 'splash' });
```
