### ISSUE TITLE
Add alias for main process

### ISSUE THREAD

**Issue by Dysey** [Deluze/electron-vue-template#15]
Hi, 

How I can add alias for main process. I tried many thing like add package 'module-alias' but not work perfectly.

For renderer process it's easy in vite.js add a resolve like

`
    resolve: {
        alias: {
            '@': Path.join(__dirname, '..', 'src', 'renderer')
        }
    }`

Thank's for you help !
Kind Regards

**Comment by Deluze** [comment]
This isn't something that works out of the box with this template, unless tsc (the typescript compiler) supports this, which I don't think it does.

You'll have to find another package to extend the build pipeline for the main process.

I've heard of node-alias before, in what way didn't it work like you thought it did?
