### ISSUE TITLE
Windows build for exe? 

### ISSUE THREAD

**Issue by timothymarois** [Deluze/electron-vue-template#2]
This is awesome work so far getting the template and the build process, everything was seamless. I'm on a mac, so I have the dmg build, but what about with the windows exe process? How might one build for that, not sure if its in the electron settings?

**Comment by timothymarois** [comment]
It looks like it only targets mac when building. Ive tried adding all the Electron build config for windows, nsis, portable etc. And the build still ignores any of those and just builds macos. I don't understand whats missing, 

```
win: {
        target: ['nsis','portable']
    },
```

Ive tried:
```
portable: {
        artifactName: "myapplication.exe"
    },
```

Nothing works. 

```
building        target=DMG arch=x64
building        target=macOS zip
```

**Comment by timothymarois** [comment]
Not sure if you can do multiple types of builds at the same time, but found that I can do 

```
return ElectronBuilder.build({
        targets: ElectronBuilder.Platform.WINDOWS.createTarget(["portable", "nsis"]),
        config: config
    });
```

On the build and it will run for windows, tested, and worked perfectly. It looks like the config by default will just run on your current platform unless you set the target above the config.

**Comment by Deluze** [comment]
You're right, the build script currently only builds for the architecture you're currently on. Cross compilation hasn't been on my mind at all.

I think a nice addition to this template would be to add new script commands that builds for given platform. e.g.: 

```bash
npm run build:win
npm run build:mac
npm run build:linux
```

It would require some changes in the build script, though. if I find the time tonight I'll create a PR that implements this @timothymarois.

**Comment by timothymarois** [comment]
@Deluze Yeah that would be a great idea! Make it more customizable for easy cross-platform! Thanks for your time on this project, definitely has saved a good amount of time with setup.

**Comment by Deluze** [comment]
Hey @timothymarois I created a PR (#3), mind trying it out?

**Comment by timothymarois** [comment]
@Deluze This works really well. thank you!
