### ISSUE TITLE
Suggestion: PR adding Eslint, VueTSC and automatic checkers?

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [Deluze/electron-vue-template#27]
Hi @Deluze, I added some conveniences to my project, and I would like to know if you are interested in a PR including:

- Eslint
- Prettier
- Vue TSC 
- Debug for VSCode (currently working only with Main Process, but as Renderer Process can use DevTools debugger, it may be sufficient for now)
- Automatic code checker when on development env, including with visual alerts inside de app:

![image](https://user-images.githubusercontent.com/11933789/192104291-752c52f5-3191-4a0e-9d58-9ad3f5ae2880.png)

**Comment by Deluze** [comment]
Whilst I'm a fan of ESLint and Vue TSC, I do want to keep this template as clean and straight forward as possible. Developers shouldn't feel the need of removing packages/files they don't want to use, which also was the reason why I decided to make my template public next to all the countless of others out there. "No unnecessary dependency overhead" actually used to be the slogan of this template.

Your suggestion is great for projects, even personal ones, though I don't think it would be a good fit for this template.

Also: I saw you added this project to the `awesome-vite` list. Thank you! It feels amazing to see others share this template in any way.
