### ISSUE TITLE
Runtime Errors

### ISSUE THREAD

**Issue by Imaginativeone** [Deluze/electron-vue-template#32]
How do I stop these runtime errors?

![Electron-Errors](https://user-images.githubusercontent.com/1640067/201651029-dd2bc9b9-4937-4284-a864-0db141309ea3.png)

**Comment by Deluze** [comment]
This output doesn't describe anything to me, I can't help you with the info you've given me. If these are not your own logs, it's probably being output by a library you're using.

Debug your application and try to find out where exceptions are being thrown.

**Comment by Deluze** [comment]
Closing this issue as it seems unrelated to this template. If that's not the case feel free to re-open.
