### ISSUE TITLE
tray icon path

### ISSUE THREAD

**Issue by xiezhengyun** [Deluze/electron-vue-template#41]
tray icon path

The path of the pallet cannot be found after packaging

<img width="274" alt="image" src="https://user-images.githubusercontent.com/22908246/215317203-8a0e91c1-63db-4bf3-9418-95ab820ace3e.png">

in createWindow function

<img width="748" alt="image" src="https://user-images.githubusercontent.com/22908246/215317240-9f11ca8a-8c73-4f66-855c-519b80425b0a.png">

How should I fill in the path

Thank you.

**Comment by Deluze** [comment]
Did you change any Electron Builder config?

By default every file in `/src/main/static` is packaged in `app.getAppPath() + '/static/...'`.

If not, unpack the `app.asar` file in `dist`. Do you see a `static` directory there?

**Comment by xiezhengyun** [comment]
I change Electron Build config, But just add main/utils && nisi && publish

```json
{
    "appId": "pacsclient",
    "directories": {
        "output": "dist"
    },
    "nsis": {
        "oneClick": false,
        "perMachine": false,
        "allowToChangeInstallationDirectory": true,
        "shortcutName": "pacsclient",
        "deleteAppDataOnUninstall": true,
        "include": "scripts/urlProtoco.nsh"
    },
    "win": {
        "target": "nsis"
    },
    "linux": {
        "target": ["snap"]
    },
    "publish": [{
        "provider": "generic",
        "url": "http://127.0.0.1:9005/"
    }],
    "files": [
        "build/main/**/*",
        {
            "from": "build/renderer",
            "to": "renderer",
            "filter": ["**/*"]
        },
        {
            "from": "src/main/static",
            "to": "static",
            "filter": ["**/*"]
        },
        {
            "from": "src/main/utils",
            "to": "utils",
            "filter": ["**/*"]
        },
        "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}",
        "!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}",
        "!**/node_modules/*.d.ts",
        "!**/node_modules/.bin",
        "!src",
        "!config",
        "!README.md",
        "!scripts",
        "!build/renderer",
        "!dist"
    ]
}
```


![image](https://user-images.githubusercontent.com/22908246/215648887-045f8a77-7122-4c03-ac2d-522e915a4eaf.png)

This is the result of packaging

'main/static/appTray' is not in result 

now i add 'renderer/public/trayIcon.png', This in 'build/renderer/trayIcon.png'

so: 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/22908246/215649977-3eb55d92-7e3c-44b9-9bbb-7f12534d3fa3.png">

this work

--------------------------
I want to make some suggestions

1. checkUpdate
2. Distinguish between production environment and test environment when packaging

**Comment by Deluze** [comment]
The `static` directory is only copied to the `build` directory when the `dev-server.js` script is ran (`npm run dev`). When the app is being packaged, the `static` directory is directly copied over from `src/main/static`.

In both production and development, static files are always available on the `app.getAppPath() + '/static/myFile.txt'`.

If you unpack the `app.asar` file, the structure should look something like this:

![image](https://user-images.githubusercontent.com/32544586/215854402-9db44000-ec22-4219-89dc-a7641fec58d7.png)

I can't immediately tell what's causing the issue you're facing. Do you have a repo with minimal reproduction?

**Comment by xiezhengyun** [comment]
Thank you very much for your patience

This is my problem. I opened the `app.asar ` file as you said, and then changed the path. It's successful

But this seems to be the same as my previous writing

But now it's all right😂

![image](https://user-images.githubusercontent.com/22908246/215990169-d8ed24ca-02c8-4dee-aa25-6491d823b159.png)

**Comment by Deluze** [comment]
> But now it's all right😂

Are you implying it works as intended now?

I tried your repository, but it seems like I can't package the app out of the box?

**Comment by Deluze** [comment]
> But now it's all right😂

Are you implying it's working as intended?

I packaged the app you sent me, the tray icon appears on both dev & packaged builds

**Comment by xiezhengyun** [comment]
Yes, no problem now
