### ISSUE TITLE
How to listen for webContents.send events from main processes in vue components

### ISSUE THREAD

**Issue by JasonYHZ** [Deluze/electron-vue-template#42]
According to the current project, I can easily use `contextBridge` from the render process to send messages from the vue process to the main process, but conversely, I do not know how to respond to the message events sent by the main process within the life cycle of the main process.

**Comment by Deluze** [comment]
Hi! I highly suggest you take a look at the IPC tutorial from Electron: https://www.electronjs.org/docs/latest/tutorial/ipc#2-expose-ipcrendereron-via-preload

The link shows you how to subscribe to an event from the main process sent through `webContents.send`

**Comment by Deluze** [comment]
Following the example in the docs:

```js
const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
    onUpdateCounter: (callback) => ipcRenderer.on('update-counter', callback)
})
```

You can use it like

```js
const msg = ref('');
window.electronAPI.onUpdateCounter((event, count) => msg.value = count.toString());
```
