### ISSUE TITLE
__name is not define

### ISSUE THREAD

**Issue by HeHong1** [Deluze/electron-vue-template#49]
when i run `npm run start`,some thing with wrong

```
09:22:42 [vite] Internal server error: __name is not defined
  Plugin: vite:vue
  File: /Users/fan/Desktop/project/timp-app/src/renderer/components/common/TitleBar.vue
```

**Comment by Deluze** [comment]
Please provide your source code as I can't tell what is going on from your error.

Also, the `npm run start` script is not something that is not from the template.
