### ISSUE TITLE
Can we add IPC practice in this template?

### ISSUE THREAD

**Issue by PublicWorld** [Deluze/electron-vue-template#50]
Hi Deluze, I'd love this template so much!
But I'd like to see how to multithread time-consuming tasks based on this template. Do you have any more examples?

**Comment by Deluze** [comment]
If you want to do some multi threading, you can spawn some worker threads after an IPC event.

Like so:

```js
ipcMain.on('start-big-task', () => {
  const worker = new Worker('path_to_big_task.js', { someData: 42 });
});
```

This example has nothing to do with the template though. I'd recommend looking into [Worker Threads](https://nodejs.org/api/worker_threads.html).
