### ISSUE TITLE
Question: How to access electron-store in vue

### ISSUE THREAD

**Issue by Chalkin** [Deluze/electron-vue-template#51]
I am using electron the first time and using your template. I love it. Thanks. But I am using Vue Pina as store and would like to implement a persistent store via electron-store similar to this blog post: [persistent vue-electron](https://medium.com/@nickpgott/creating-a-persistent-store-you-can-use-across-components-with-vuex-and-electron-store-1dd561444302) I am struggling to access electron store in Vue.js. 

It's starting with the error message: 

```
Uncaught ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (index.js:4:28)
    at __require2 (chunk-7FP5O474.js?v=6a998cbc:10:50)
    at node_modules/electron-store/index.js (index.js:3:44)
    at __require2 (chunk-7FP5O474.js?v=6a998cbc:10:50)
    at index.js:81:18
```
    
when I init the electron store in my pina store:
    
```
import Store from "electron-store";
const persistentStore = new Store();
```
    

Maybe you have an idea?

**Comment by Deluze** [comment]
I'm not familiar with Electron Store, I read a bit through their README and read the following:

> You can use this module directly in both the main and renderer process. For use in the renderer process only, you need to call Store.initRenderer() in the main process, or create a new Store instance (new Store()) in the main process.

Have you tried this? By default `nodeIntegration` is turned off, so you can't import node libraries into the front-end.

**Comment by Chalkin** [comment]
I found the solution by basically following this: [React electron-store](https://electron-react-boilerplate.js.org/docs/electron-store)

main/main.ts
```
import ElectronStore from 'electron-store';
const electronStore = new ElectronStore();

...
ipcMain.on('electron-store-get', async (event, val) => {
  event.returnValue = electronStore.get(val);
});

ipcMain.on('electron-store-set', async (event, key, val) => {
  electronStore.set(key, val);
});
```

main/preload.ts
```
....
contextBridge.exposeInMainWorld('electron', {
  store: {
    get(key) {
      return ipcRenderer.sendSync('electron-store-get', key);
    },
    set(property, val) {
      ipcRenderer.send('electron-store-set', property, val);
    },
    // Other method you want to add like has(), reset(), etc.
  },
  // Any other methods you want to expose in the window object.
  // ...
});
```

Adding this to the interface Window in renderer/typings/electron.d.ts

```
    electron: {
      store: {
        get: (key: string) => any;
        set: (key: string, val: any) => void;
        // any other methods you've defined...
      };
    };
  }

**Comment by Deluze** [comment]
I would also have suggested to take the IPC route.

Closing this as it's resolved.
