### ISSUE TITLE
for someone who needs to use@electron/remote

### ISSUE THREAD

**Issue by FanLu1994** [Deluze/electron-vue-template#52]
1. install vite-plugin-electron-renderer
`
npm install vite-plugin-electron-renderer
`

2. change vite config
```
...
import renderer from 'vite-plugin-electron-renderer'
...
const config = defineConfig({
  ...
  plugins: [vuePlugin(),renderer()],
  ...
})
```

**Comment by Deluze** [comment]
Closing this issue as it's a small example that they it's in the readme of `vite-plugin-electron-renderer` itself.
Also not relevant to the template.

I appreciate sharing your findings. Feel free to share this in the discussions tab for others to find :)
