### ISSUE TITLE
Delete package file related

### ISSUE THREAD

**Issue by nanfb** [Deluze/electron-vue-template#63]
![image](https://github.com/Deluze/electron-vue-template/assets/56207464/9adbec57-5cb9-4b8c-aa67-619108d768b4)

![image](https://github.com/Deluze/electron-vue-template/assets/56207464/11fcaae3-372d-497f-8523-9cf8992d1282)

dist_electron file will be generated in the root path after packaging, but I want to delete it in vscode, there is an app.asar file that is locked and cannot be deleted, and it can only be deleted after vscode is closed, and it will affect repeated packaging, that is, if the package file is not deleted after packaging, then continue packaging. You'll get an error because of that

**Comment by Deluze** [comment]
I don't have vscode installed. 

Are you building the app through your CLI, or are you running some vscode tasks?
I'm not sure how to verify this issue.. a bit odd-sounding that vscode has a file handle open to that file..

Do you perhaps have some vscode extensions installed that could be causing this?

**Comment by nanfb** [comment]
> 我没有安装 vscode。
> 
> 您是通过 CLI 构建应用程序，还是正在运行一些 vscode 任务？ 我不确定如何验证这个问题。听起来有点奇怪，vscode 有一个打开该文件的文件句柄。
> 
> 您是否安装了一些可能导致此问题的 vscode 扩展？

I don’t know. After I modified the packaging configuration file of electron, it became normal. It’s strange.
