### ISSUE TITLE
The next button style of the installation package is abnormal 

### ISSUE THREAD

**Issue by fly-bue** [Deluze/electron-vue-template#64]
![image](https://github.com/Deluze/electron-vue-template/assets/54001753/12e47043-2549-498e-b15b-357ccc5e2e84)

**Comment by Deluze** [comment]
Try updating the `electron-builder` package

**Comment by fly-bue** [comment]
@Deluze Thanks for the reply. I upgraded the version to 25.0.0-alpha.10, the problem still exists.

**Comment by Deluze** [comment]
> @Deluze Thanks for the reply. I upgraded the version to 25.0.0-alpha.10, the problem still exists.

My bad for the late reply. This is an issue with the NSIS installer; https://nsis.sourceforge.io/Main_Page
This issue can't be fixed in this template, so I'll be closing the issue.
