### ISSUE TITLE
dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.

### ISSUE THREAD

**Issue by somethino** [Deluze/electron-vue-template#69]
I cloned your project and am getting this error when building.

![image](https://github.com/user-attachments/assets/945127cd-6af4-40b2-bbf7-beef28219e6d)

**Comment by Deluze** [comment]
It says the entrypoint file `main/main.js` can't be found. Did you rename/remove the `main.js` file from the main directory?
